FIS2425/staff-svc

- openapi.yaml
- src/api.js
- src/controllers/doctorController.js
- src/routes/doctorRoute.js
This pull request introduces a new feature to allow deleting a registered doctor. Key changes include adding a new endpoint for deleting a doctor, implementing the backend logic, and handling errors and logging for better traceability.
-  Implemented `deleteDoctor` function in `src/controllers/doctorController.js` Searches for the doctor by doctorId from the request parameters then deletes the doctor.
- Added a new route `/:doctorId` in `src/routes/doctorRoutes.js` to handle the DELETE request that invokes the deleteDoctor function.
> feat: delete doctor

- openapi.yaml
- src/controllers/doctorController.js
- src/routes/doctorRoute.js
This pull request introduces a new feature to allow updating the specialty of an already registered doctor. Key changes include adding a new endpoint for updating the specialty, implementing the backend logic, and handling errors and logging for better traceability.
-  Implemented `updateDoctorSpeciality` function in `src/controllers/doctorController.js` Searches for the doctor by doctorId from the request parameters then updates the doctor's specialty field and saves the changes.
- Added a new route `/:doctorId/update` in `src/routes/doctorRoutes.js` to handle the PUT request that invokes the updateDoctorSpeciality function.
> feat: update speciality of a doctor

- openapi.yaml
- src/controllers/doctorController.js
- src/routes/doctorRoute.js
This pull request introduces updates to the doctorController to enhance logging for better traceability and debugging. Additionally, minor updates have been made to the routes in `doctorRoute.js`.
- Consistent Logging Structure:
Updated the logging in the `updateDoctorSpeciality`,` deleteDoctor`, and `getDoctorsBySpeciality` functions to include detailed information such as method, URL, IP address, and error messages. This follows the logging structure used in the register function for consistency.
- Routes: Updated the routes in `doctorRoute.js` to ensure proper mapping to the controller functions.
> refactor: logger updated

- .github/workflows/trigger-api-sync.yml
This Pull Request includes the changes made through a cherry-pick of a specific commit from the template repository (474dcfd5f2fd08ca79d21e134b5d82183e051407) to update the OpenAPI specification of the API Gateway.
> Chore: Update Openapi of Api Gateway

- tests/unit/controllers/staff.test.js
This pull request introduces unit tests for the Doctor registration and management functionalities. The tests ensure proper validation, creation, retrieval, updating, and deletion of doctors.
POST /staff/register:
- Added tests to ensure proper validation and creation of doctors.
- Verified that a 400 Bad Request is returned if required fields are missing.
- Verified that a 201 Created is returned if all required fields are provided.
GET /staff/clinic/:clinic/speciality/:speciality?:
- Added tests to verify the retrieval of doctors by clinic and speciality.
- Verified that a 200 OK is returned with the list of doctors for a given clinic and speciality.
- Verified that a 404 Not Found is returned if no doctors are found for the given clinic and speciality.
PUT /staff/:doctorId:
- Added …
> test: Add unit test for staff controller

- .env.example
- package-lock.json
- package.json
- src/controllers/doctorController.js
- src/middleware/verifyAdmin.js
- src/middleware/verifyAuth.js
- src/routes/doctorRoute.js
- src/utils/validation.js
This Pull Request integrates the authentication microservice into our existing API. The changes include setting up middleware for authentication and authorization, and updating routes to ensure secure access.
1. **Middleware Integration**:
- Added `verifyAuth` middleware to handle authentication using JWT tokens.
- Added `verifyAdmin` middleware to ensure that only users with the `clinicadmin` role can perform certain actions.
2. **Route Updates**:
- Updated the `/register`, `/updateDoctorSpeciality`, and `/deleteDoctor` routes to include authentication and authorization checks.
- Ensured that only authenticated users with the appropriate roles can access these routes.
3. **Controller Updates**:
- Modified the `register` function to create a user in the auth microservice when a new doctor …
> Feat: Integration with auth service

- src/controllers/doctorController.js
- src/routes/doctorRoute.js
- src/schemas/Doctor.js
- tests/unit/controllers/staff.test.js
This Pull Request addresses the issues with the `clinic` and `userId` attributes in the `Doctor` model. The changes ensure that these attributes are correctly validated and handled within the application.
1. **Model Updates**:
- Updated the `Doctor` model to ensure proper validation and handling of the `clinic` and `userId` attributes.
- Added validation to ensure that the `clinic` attribute is a valid UUID.
- Ensured that the `userId` attribute is required and properly validated.
- Updated name clinic to clinicId
2. **Controller Updates**:
- Modified the `register` function to correctly handle the `clinicId` and `userId` attributes when creating a new doctor.
- Updated the `deleteDoctor` function to ensure the `userId` attribute is correctly used when interacting with the auth …
> Fix: Id attributes from doctor model

- src/schemas/Doctor.js
- tests/unit/schemas/doctor.test.js
This Pull Request tests the validations made by the schema Doctor.
1. **Schema Test**:
- `doctor.test.js` file created to test every validation.
> Test: testing schema

- package-lock.json
- package.json
- src/controllers/doctorController.js
- src/utils/validation.js
- tests/setup/setup.js
- tests/unit/controllers/staff.test.js
- tests/unit/schemas/doctor.test.js
This Pull Request includes changes to mock the middleware and the calls to the authentication microservice in the controller, ensuring that the tests now run successfully without requiring actual connections to the external services.
1. **Middleware Mocking**:
- Mocked the `verifyAuth` middleware to simulate JWT token verification.
- Mocked the `verifyAdmin` middleware to simulate role-based access control.
2. **Mocking Calls to Authentication Microservice**:
- Used `nock` to mock the HTTP requests to the authentication microservice.
- Ensured that the `POST /users` and `DELETE /users/:id` endpoints are mocked to return appropriate responses.
> Test: fix tests which do not work because of auth integration

- tests/unit/controllers/staff.test.js
This Pull Request includes two new tests to verify the functionality of the `getMe` endpoint. These tests ensure that the endpoint correctly returns the authenticated doctor's information and handles cases where the token belongs to another doctor.
1. **Added Tests for `getMe` Endpoint**:
- Created a test to verify that the `getMe` endpoint returns the correct doctor's information when a valid token is provided.
- Created a test to verify that the `getMe` endpoint returns a 404 status code when the token belongs to another doctor.
> Test:  getMe controller

- src/utils/validation.js
- tests/unit/controllers/staff.test.js
- tests/unit/schemas/doctor.test.js
This Pull Request includes changes to the `validation.js` file to enhance the password validation logic. The updated validation ensures that passwords meet specific criteria, including length, character types, and the absence of spaces.
1. **Password Validation Enhancement**:
- Updated the password validation to require a minimum length of 8 characters and a maximum length of 32 characters.
- Added a regex pattern to ensure the password contains at least one uppercase letter, one lowercase letter, one number, and one special character.
- Added a custom validation to ensure the password does not contain any spaces.
> Feat: password validation added to register

- .env.example
- docker-compose.yml
- tests/unit/controllers/staff.test.js
- tests/unit/schemas/doctor.test.js
This Pull Request includes updates to the `docker-compose.yml` file, removal of `console.log` statements from tests, and updates to the `.env.example` file. These changes improve the configuration and cleanliness of the codebase.
1. **Update `docker-compose.yml`**:
- Updated the `docker-compose.yml` file to ensure proper configuration of services and environment variables.
2. **Remove `console.log` Statements from Tests**:
- Removed unnecessary `console.log` statements from the test files to clean up the output and improve readability.
3. **Update `.env.example`**:
- Updated the `.env.example` file to reflect the necessary environment variables and their default values.
- **docker-compose.yml**:
- Ensured proper configuration of the `mongodb` and `staff-svc` services.
- Added necessary …
> Chore: 50 update docker compose, delete console.log from tests, update .env.example

- src/controllers/doctorController.js
- src/middleware/verifyAuth.js
This Pull Request includes updates to the `register` function in the `doctorController.js` file to ensure that a user is not created without first ensuring that the doctor is successfully created. Additionally, the `req.token` has been removed as `req.cookies.token` already exists and is being used.
1. **Update `register` Function**:
- Modified the `register` function to ensure that a user is not created without first ensuring that the doctor is successfully created.
- Added error handling to roll back the user creation if the doctor creation fails.
2. **Remove `req.token`**:
- Removed `req.token` as `req.cookies.token` already exists and is being used for authentication.
> Feat: register integration updated and req.token deleted

- .env.example
- src/api.js
- tests/unit/controllers/staff.test.js
This Pull Request includes changes to add an API prefix to the application by modifying the `.env.example` file, `api.js`, and `staff.test.js`. These changes ensure that all API routes are prefixed with a consistent base path, improving the organization and accessibility of the API endpoints.
1. **Update `.env.example`**:
- Added `API_PREFIX` to the `.env` file to define the base path for all API routes.
2. **Modify `api.js`**:
- Updated the `api.js` file to use the `API_PREFIX` environment variable for routing.
- Ensured that all routes are prefixed with the value of `API_PREFIX`.
3. **Update `staff.test.js`**:
- Modified the test cases in `staff.test.js` to use the `API_PREFIX` environment variable for making requests.
> CHORE: add api prefix to the app

- src/utils/kafkaTransport.js
This Pull Request includes changes made via a cherry-pick from a specific commit to fix issues related to Kafka logging. The changes ensure that Kafka logging is correctly implemented and functional.
1. **Kafka Logging Fix**:
- Cherry-picked [this commit](https://github.com/FIS2425/template/commit/5829224c) to fix the Kafka logging implementation.
- Ensured that the Kafka producer connects, sends messages, and disconnects properly.
> Chore: fix kafka

- .github/workflows/test.yml
This Pull Request includes updates to the GitHub Actions workflow to ensure that only unit tests are run during the CI process. This change helps to streamline the testing process and reduce the time required for CI runs.
1. **Update GitHub Actions Workflow**:
- Modified the `test.yml` workflow file to run only unit tests during the CI process.
- **test.yml**:
- Updated the workflow to include a step that runs only unit tests using the `npm run test:unit` command.
> chore(staff): tests workflow only check unit tests

- .github/workflows/test.yml
This Pull Request updates the tests workflow to add environment variables so that the tests work properly.
- Added to `tests.yml` workflow the following environment variables: AUTH_SVC, VITE_AUTH_SVC, API_PREFIX, VITE_API_PREFIX, JWT_SECRET, VITE_JWT_SECRET
> Chore: tests workflow envs added

- .env.example
- .github/workflows/test.yml
- src/api.js
- src/controllers/doctorController.js
- tests/integration/db.test.js
- tests/unit/controllers/staff.test.js
This Pull Request includes the removal of unnecessary environment variables used for tests and the refactoring of the code to ensure that the tests continue to function correctly. These changes help to simplify the configuration and improve the maintainability of the codebase.
1. **Removed Unnecessary Environment Variables**:
- Removed environment variables that were not needed for the tests from the [`.env.example`](.env.example ) file.
- VITE_API_PREFIX and VITE_AUTH_SVC deleted
2. **Refactored Code to Ensure Tests Function Correctly**:
- Updated the code to remove dependencies on the unnecessary environment variables.
- Ensured that all tests continue to function correctly after the removal of the environment variables.
> Refactor: delete environment variables that are not neccessary for testing

- package.json
This Pull Request includes updates to the `npm start` script in the `package.json` file to ensure that it does not require an `.env` file. This change simplifies the startup process and makes it more flexible for different environments.
1. **Update `npm start` Script**:
- Modified the `npm start` script in the `package.json` file to remove the dependency on the `.env` file.
> Hotfix: npm start script updated

- populators/runPopulator.js
- src/controllers/doctorController.js
- src/utils/validation.js
- tests/unit/controllers/staff.test.js
This Pull Request includes updates to the `register` function in the `doctorController.js` file to ensure that a doctor is created using the clinicId of the clinicadmin instead of a clinicId on the body. It also creates a populator.
1. **Update `register` Function**
2. **Update validation**
3. **Update tests**
4. **Creates populator**
> Feat: register without clinicId in body and populator

- .dockerignore
- .gitignore
- kubernetes/mongo-data-staff-persistentvolumeclaim.yaml
- kubernetes/mongodb-deployment.yaml
- kubernetes/mongodb-service.yaml
- kubernetes/staff-svc-deployment.yaml
- kubernetes/staff-svc-service.yaml
- populators/runPopulator.js
- src/controllers/doctorController.js
- src/utils/validation.js
- tests/unit/controllers/staff.test.js
> Revert "Revert "Feat: populator and register withput clinicId in body""

- populators/runPopulator.js
This Pull Request includes updates to the `runPopulator` file to add definite ids to the doctors.
> Feat: add ids to populator

- openapi.yaml
This pull request updates the `openapi.yaml` file to modify the URL for the production server.
> Docs: openapi updated

- kubernetes/staff-svc-deployment.yaml
- kubernetes now uses latest image for staff-svc
> Hotfix: kubernetes uses latest image

- src/api.js
- src/config/logger.js
- src/utils/kafkaTransport.js
> Feat: cherry pick 

- .env.example
- kubernetes/staff-svc-deployment.yaml
- populators/runPopulator.js
- src/controllers/doctorController.js
- tests/unit/controllers/staff.test.js
Feature toggle to check if a staff can be registered depending on the plan purchased by the clinic
> Feat: feature toggle added

- .github/workflows/deploy-aks.yaml
- package-lock.json
- package.json
- Workflow to deploy service to aks added
> Feat: add workflow to deploy in aks

- .github/workflows/deploy-aks.yaml
- package-lock.json
- package.json
> Fix(staff): workflow to deploy
